### ISSUE TITLE
部分嵌入文章中的代码在移动端无法正常显示

### ISSUE THREAD

**Issue by xiaomage2000** [AlanDecode/Typecho-Theme-RAW#8]
这个响应式主题很棒，用了有两三个月了~

但最近发现在手机上，最新的手机Chrome浏览器下，部分插入文章中的代码无法正常显示，显示为空白，可以使用电脑上的开发者工具左上角的toggle device toolbar复现。具体情况请看图片。
![2019-04-14 (4)](https://user-images.githubusercontent.com/13915895/56092416-76cec300-5eee-11e9-9bde-0d6c06ca91f0.png)
![Screenshot_20190414-192433](https://user-images.githubusercontent.com/13915895/56092424-8fd77400-5eee-11e9-91ab-f1c50bab1681.jpg)

我尝试着想修复，但以失败告终...有空的话，烦请看一下啥情况~

**Comment by xiaomage2000** [comment]
补充下，在Firefox浏览器下正常，另外也排除了插件的影响，插件都尝试停用过了~

**Comment by AlanDecode** [comment]
我无法复现这个bug...从你的截图来看没有什么问题啊，看上去像是浏览器渲染的问题。RAW 的渲染效率确实比较低下。

**Comment by xiaomage2000** [comment]
emmm...应该就是渲染的问题，更改部分样式后就相对正常了
